name: Automerge completed pull requests

on:
    pull_request:
        types:
          - labeled
          - synchronize
          - edited
    pull_request_review:
        types:
          - submitted
    check_suite:
        types:
          - completed
    status: {}

jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
          # https://github.com/marketplace/actions/merge-pull-requests
          - name: Automerge completed pull requests
            uses: "pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a"
            env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                MERGE_FILTER_AUTHOR: ompiteam-bot
                MERGE_DELETE_BRANCH: True
                # RETRY_SLEEP is in miliseconds
                MERGE_RETRY_SLEEP: 10000
                MERGE_RETRIES: 100
