name: GitHub Action CI

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, edited]

jobs:
    ci:
        name: Git commit checker
        # if: ${{ github.event.issue.pull_request }}
        # Meaningless change
        runs-on: ubuntu-latest
        steps:
          - name: show the environment
            run: env | sort

          - uses: khan/pull-request-comment-trigger@master
            id: check
            with:
              trigger: 'bot:retest'
              reaction: rocket
            env:
              GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

          - run: 'echo Found it!'
            if: steps.check.outputs.triggered == 'true'

          - name: Check out the code
            uses: actions/checkout@v2
            with:
                # Get all branches and history
                fetch-depth: 0

          - name: Setup Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'

          - name: Get the GitPython and PyGithub modules
            run: pip install gitpython PyGithub

          - name: Check all git commits
            run: $GITHUB_WORKSPACE/.github/workflows/git-commit-checks.py
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
