name: GitHub Action CI

on:
  issue_comment:
  pull_request:
        types:
          - opened
          - synchronize
          - edited

jobs:
    ci:
        name: Git commit checker
        # if: ${{ github.event.issue.pull_request }}
        runs-on: ubuntu-latest
        steps:
          - name: Check out the code
            uses: actions/checkout@v2
            with:
                # Get all branches and history
                fetch-depth: 0

          - name: List open pull requests -- only in a repo!
            run: hub pr list
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Setup Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'

          - name: Get the GitPython and PyGithub modules
            run: pip install gitpython PyGithub

          - name: Check all git commits
            run: $GITHUB_WORKSPACE/.github/workflows/git-commit-checks.py
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
