name: GitHub Action CI

on:
    pull_request:
        # We don't need this to be run on all types of PR behavior
        # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
        types:
          - opened
          - synchronize
          - edited

on:
    issue_comment:
        # We also want this check run any time anyone adds a comment
        # to a PR.  We can't seem to filter on when a comment is
        # created/edited that contains a magic token like
        # "bot:retest", so just run it *every* time for
        # simplicity. The check is short enough that this doesn't seem
        # to matter.
        # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment
        types:
          - created
          - edited

jobs:
    ci:
        name: Git commit checker
        runs-on: ubuntu-latest
        steps:
          - name: Check out the code
            uses: actions/checkout@v2
            with:
                # Get all branches and history
                fetch-depth: 0

          - name: List open pull requests -- only in a repo!
            run: hub pr list
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Setup Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'

          - name: Get the GitPython and PyGithub modules
            run: pip install gitpython PyGithub

          - name: Check all git commits
            run: $GITHUB_WORKSPACE/.github/workflows/git-commit-checks.py
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
