name: Git commit checker

on:
    pull_request:
        # We don't need this to be run on all types of PR behavior
        # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
        types:
          - opened
          - synchronize
          - edited

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
          - name: Check out the code
            uses: actions/checkout@v2
            with:
                # Get all branches and history
                fetch-depth: 0

          - name: Setup Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'

          - name: Get the GitPython module
            run: pip install gitpython

          - name: Download PR main description text
            uses: octokit/request-action@v2.x
            id: get_pr_body
            with:
              route: GET /repos/${{ github.repository }}/pulls/${{ github.event.number }}
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Check all git commits
            run: |
              if test "${{ contains(fromJson(steps.get_pr_body.outputs.data).body, 'bot:notacherrypick') }}" = "true"; then
                  arg="--notacherrypick"
              fi
              $GITHUB_WORKSPACE/.github/workflows/git-commit-checks.py $arg
