name: Make pull requests on md2nroff branches

on:
  push:
    branches:
      - master

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "md2nroff/"
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_BODY: "The nroff elves created these man pages, just for you!"
          PULL_REQUEST_TITLE: "Update nroff-generated man pages"
