name: Generate nroff man pages from Markdown files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-to-nroff:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Pandoc
      run: |
        sudo apt install -y pandoc

    - name: Find files
      run: |
        files=`find . -name \*\.[123456789]\.md`
        echo files: $files
        for file in $files; do
            outfile=`echo $file | sed -e 's/.md//'`
            ./md2nroff.pt --source $file --dest $outfile
        done

    - name: Run Pandoc
      run: |
        pandoc --version
        pandoc --from=markdown --to=man --output=fabric.7 fabric.7.md

    - name: Upload artifacts to Github
      uses: actions/upload-artifact@master
      with:
        name: fabric.7
        path: fabric.7
