name: Generate nroff man pages from Markdown files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-to-nroff:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Make sure output directory exists
      run: mkdir output

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Setup and run Pandoc
      uses: docker://pandoc/core:2.9
      with:
        args: "--from=markdown --to=man --output=output/fabric.7 fabric.7.md"

    - name: Run in Pandoc container
      uses: docker://pandoc/core:2.9
      run: |
        pandoc --version
        pwd
        ls -l

    - name: Upload artifacts to Github
      uses: actions/upload-artifact@master
      with:
        name: output
        path: output
