name: Generate nroff man pages from Markdown files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-to-nroff:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Pandoc
      run: |
        sudo apt install -y pandoc

    - name: Find all Markdown man pages and run Pandoc on them
      run: |
        files=`find . -name \*\.[123456789]\.md`
        echo files: $files
        for file in $files; do
            outfile=`echo $file | sed -e 's/.md//'`
            ./md2nroff.py --source $file --dest $outfile
            git add $outfile
        done

    - name: Try to git commit
      run: |
        git config --global user.name 'Open MPI Bot'
        git config --global user.email 'ompi-bot@open-mpi.org'
        git commit -s -m 'Updated nroff-generated man pages' || touch not-needed
        if test -f not-needed; then
            echo the git commit was not needed
        else
            echo we needed the git commit
        fi

    - name: Try to git commit 2nd time
      run: |
        git config --global user.name 'Open MPI Bot'
        git config --global user.email 'ompi-bot@open-mpi.org'
        git commit -s -m 'Updated nroff-generated man pages' || touch not-needed
        if test -f not-needed; then
            echo the git commit was not needed
        else
            echo we needed the git commit
        fi

    - name: Are we still here?
      run: |
        echo we are still here
        uptime

    - name: Upload artifacts to Github
      uses: actions/upload-artifact@master
      with:
        name: fabric.7
        path: fabric.7
